### ISSUE TITLE
A bug when creating entity_strings.txt for wikidata5m

### ISSUE THREAD

**Issue by Neo-Zhangjiajie** [apoorvumang/kgt5#2]
when I creat entity_strings.txt for wikidata5m, it reports a bug.

`python /home/zjj/kgt5/data/get_unique_entities.py --dataset wikidata5m
285780it [00:00, 596976.79it/s]
Traceback (most recent call last):
  File "/home/zjj/kgt5/data/get_unique_entities.py", line 26, in <module>
    unique_entities.add(split_sentence[1].strip())
IndexError: list index out of range`

And I output this line in train.txt, it is
 `predict tail: creation | destruction | instance of |     bonus tracks`

So how do I solve this? Just skip this line?

**Comment by apoorvumang** [comment]
Yeah that's a bug since the entity representation here also contains the symbol '|'. This was fixed in a subsequent dataset revision (we will upload that soon)

For now, you can skip this line I think (other option would be to look for entity 'creation | destruction' and remove the symbol '|' from it, but this is not ideal).
