### ISSUE TITLE
How is T5 randomly initialised and NOT using pretrained LM weights?

### ISSUE THREAD

**Issue by sm354** [apoorvumang/kgt5#7]
Hi Apoorv,

I am trying to locate where the T5 is randomly initialised (using transformers library). I think [this line](https://github.com/apoorvumang/kgt5/blob/d660dce63133f0fd3fa4d909c92b27dad6395153/main_accelerate.py#L138) loads the pretrained weights. Could you please tell how and where the randomly-initialised weights are loaded?

[This](https://github.com/huggingface/transformers/issues/4701) also explains that `from_pretrained` method loads the pretrained weights.

**Comment by sm354** [comment]
[This](https://stackoverflow.com/questions/65072694/make-sure-bert-model-does-not-load-pretrained-weights) post does the same as in your [line of code](https://github.com/apoorvumang/kgt5/blob/d660dce63133f0fd3fa4d909c92b27dad6395153/main_accelerate.py#L138). I also manually checked that the parameters are different in the two ways: `AutoModel.from_config` and `AutoModel.from_pretrained`. Could you please confirm this?

**Comment by apoorvumang** [comment]
Hi Shubham

Pretrained weights are not loaded when loading with config (see https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/t5#transformers.T5ForConditionalGeneration). In the current code, as you pointed out, model is loaded as follows
```
config = T5Config().from_pretrained('t5-small')
model = T5ForConditionalGeneration(config)
```
This is not the same as  ``model = T5ForConditionalGeneration.from_pretrained('t5-small')``.  In our case, from_pretrained method of T5ForConditionalGeneration is not called, hence weights aren't loaded.

I confirmed this in a colab notebook here: https://colab.research.google.com/drive/1Gh5gbp6tl9P-DBHQ_ottV2rBVMB_gSRU?usp=sharing. You can first try generating from the model loaded using the config route (as is done in KGT5 code) and it generates garbage. If you switch to ``model = T5ForConditionalGeneration.from_pretrained('t5-small')``, you can see that it outputs meaningful generations.

Please let me know if you still have doubts on whether it is initialized with pretrained weights or not. Also, I would suggest you look into the 'apoorv-dump' branch instead of main if you want to see a more updated codebase (but its not clean). In that branch, there is a specific flag for enabling the use of pretrained LM weights. I will try and update to using ``AutoModel.from_config`` to make it clear that weights aren't loaded, thanks for the suggestion.

**Comment by sm354** [comment]
Thanks for the confirmation! Closing the issue.
